<?php
/**
 * Web installer – the first-run wizard, in the spirit of WordPress.
 * Collects database details, creates the database + tables, creates the
 * admin account and writes config.php. Locks itself once config.php exists.
 */

declare(strict_types=1);

require __DIR__ . '/includes/bootstrap.php';
fb_security_headers();
fb_session();

$errors  = [];
$done    = false;
$values  = [
    'db_host' => 'localhost', 'db_name' => 'flying_bird', 'db_user' => '', 'db_prefix' => 'fb_',
    'site_title' => 'Flying Bird', 'admin_user' => 'admin',
];

$checks = [
    'PHP 7.4 or newer'            => PHP_VERSION_ID >= 70400,
    'PDO MySQL extension'         => extension_loaded('pdo_mysql'),
    'mbstring extension'          => extension_loaded('mbstring'),
    'Folder is writable (config)' => is_writable(FB_ROOT),
    'database/schema.sql found'   => is_file(FB_ROOT . '/database/schema.sql'),
];
$ready = !in_array(false, $checks, true);

if (fb_installed()) {
    $state = 'locked';
} elseif ($_SERVER['REQUEST_METHOD'] === 'POST' && $ready) {
    $state = 'form';
    if (!fb_csrf_valid($_POST['csrf'] ?? null)) {
        $errors[] = 'Your session expired. Please try again.';
    }
    foreach (array_keys($values) as $k) {
        $values[$k] = trim((string) ($_POST[$k] ?? ''));
    }
    $dbPass = (string) ($_POST['db_pass'] ?? '');
    $adminPass = (string) ($_POST['admin_pass'] ?? '');

    if ($values['db_host'] === '' || $values['db_name'] === '' || $values['db_user'] === '') {
        $errors[] = 'Database host, name and user are required.';
    }
    if (!preg_match('/^[A-Za-z0-9_]+$/', $values['db_name'])) {
        $errors[] = 'Database name may only contain letters, numbers and underscores.';
    }
    if (!preg_match('/^[A-Za-z0-9_]{0,20}$/', $values['db_prefix'])) {
        $errors[] = 'Table prefix may only contain letters, numbers and underscores (max 20).';
    }
    if (!preg_match('/^[A-Za-z0-9_.-]{3,60}$/', $values['admin_user'])) {
        $errors[] = 'Admin username must be 3–60 characters (letters, numbers, . _ -).';
    }
    if (strlen($adminPass) < 8) {
        $errors[] = 'Admin password must be at least 8 characters.';
    }
    if ($adminPass !== (string) ($_POST['admin_pass2'] ?? '')) {
        $errors[] = 'The admin passwords do not match.';
    }

    if (!$errors) {
        try {
            // 1. Connect to the server and create the database if we may.
            $server = fb_connect($values['db_host'], $values['db_user'], $dbPass);
            try {
                $server->exec('CREATE DATABASE IF NOT EXISTS `' . $values['db_name'] . '` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci');
            } catch (PDOException $e) {
                // No CREATE privilege: fine if the database already exists.
            }
            $pdo = fb_connect($values['db_host'], $values['db_user'], $dbPass, $values['db_name']);

            // 2. Write config first so the db helpers know the table prefix.
            $config = [
                'db_host'   => $values['db_host'],
                'db_name'   => $values['db_name'],
                'db_user'   => $values['db_user'],
                'db_pass'   => $dbPass,
                'db_prefix' => $values['db_prefix'],
                'salt'      => bin2hex(random_bytes(16)),
            ];

            // 3. Create tables.
            fb_install_schema($pdo, $values['db_prefix']);

            // 4. Seed settings + admin account.
            $t = static fn (string $n): string => '`' . $values['db_prefix'] . $n . '`';
            $settings = fb_setting_defaults();
            $settings['site_title'] = $values['site_title'] !== '' ? mb_substr(strip_tags($values['site_title']), 0, 60) : 'Flying Bird';
            $pdo->prepare('REPLACE INTO ' . $t('settings') . ' (`name`,`value`) VALUES (?,?)')->execute(['settings', json_encode($settings)]);
            $pdo->prepare('REPLACE INTO ' . $t('settings') . ' (`name`,`value`) VALUES (?,?)')->execute(['db_version', (string) FB_DB_VERSION]);
            $pdo->prepare('INSERT INTO ' . $t('users') . ' (username, password_hash, created_at) VALUES (?,?,?)')
                ->execute([$values['admin_user'], password_hash($adminPass, PASSWORD_DEFAULT), gmdate('Y-m-d H:i:s')]);

            // 5. Write config.php last: its existence marks the install as complete.
            $php = "<?php\n// Generated by install.php. Delete this file to run the installer again.\nreturn " . var_export($config, true) . ";\n";
            $tmp = FB_CONFIG_FILE . '.tmp';
            if (file_put_contents($tmp, $php, LOCK_EX) === false || !rename($tmp, FB_CONFIG_FILE)) {
                throw new RuntimeException('Could not write config.php. Make the folder writable and retry.');
            }
            @chmod(FB_CONFIG_FILE, 0640);
            $done = true;
            $state = 'done';
        } catch (Throwable $e) {
            $msg = $e instanceof PDOException ? 'Database error: ' . $e->getMessage() : $e->getMessage();
            $errors[] = $msg;
        }
    }
} else {
    $state = 'form';
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="robots" content="noindex">
    <title>Install · Flying Bird</title>
    <link rel="stylesheet" href="css/site.css">
</head>
<body class="fb-body">
<main class="fb-shell">
    <div class="fb-panel fb-narrow">
        <h1 class="fb-h1">Flying Bird</h1>

        <?php if ($state === 'locked'): ?>
            <p class="fb-muted">Already installed. To run the installer again, delete <code>config.php</code>.</p>
            <p><a class="fb-btn" href="index.php">Play the game</a></p>

        <?php elseif ($state === 'done'): ?>
            <p class="fb-ok">Installed. The database tables were created and your admin account is ready.</p>
            <p><a class="fb-btn" href="index.php">Play the game</a></p>
            <p><a class="fb-btn fb-btn-ghost" href="admin.php">Open settings</a></p>
            <p class="fb-muted">For safety you may delete <code>install.php</code> now.</p>

        <?php else: ?>
            <p class="fb-muted">One-minute set-up. Enter your MySQL / MariaDB details and Flying Bird will create the database tables for you. No SQL import needed.</p>

            <ul class="fb-checks">
                <?php foreach ($checks as $label => $ok): ?>
                    <li class="<?= $ok ? 'is-ok' : 'is-bad' ?>"><?= fb_h($label) ?></li>
                <?php endforeach; ?>
            </ul>

            <?php foreach ($errors as $err): ?>
                <div class="fb-alert" role="alert"><?= fb_h($err) ?></div>
            <?php endforeach; ?>

            <form method="post" class="fb-form-stack" autocomplete="off">
                <?= fb_csrf_field() ?>
                <h2 class="fb-h2">Database</h2>
                <label>Host <input name="db_host" value="<?= fb_h($values['db_host']) ?>" required></label>
                <label>Database name <input name="db_name" value="<?= fb_h($values['db_name']) ?>" required></label>
                <label>Username <input name="db_user" value="<?= fb_h($values['db_user']) ?>" required></label>
                <label>Password <input name="db_pass" type="password"></label>
                <label>Table prefix <input name="db_prefix" value="<?= fb_h($values['db_prefix']) ?>"></label>

                <h2 class="fb-h2">Site</h2>
                <label>Site title <input name="site_title" value="<?= fb_h($values['site_title']) ?>"></label>
                <label>Admin username <input name="admin_user" value="<?= fb_h($values['admin_user']) ?>" required></label>
                <label>Admin password <input name="admin_pass" type="password" minlength="8" required></label>
                <label>Repeat password <input name="admin_pass2" type="password" minlength="8" required></label>

                <button class="fb-btn" type="submit"<?= $ready ? '' : ' disabled' ?>>Install</button>
            </form>
        <?php endif; ?>
    </div>
</main>
</body>
</html>
